$kind: apps.supos.com;v1alpha1:Application
$metadata:
  name: data-insight-agent
group: datainsight
type: agent
showName: 数据洞察智能体
version: 0.0.1
vendor:
  name: supos
  showName: supos-developer
  email: developer@supos.com
  url: https://supos.com
  bluetronId: 123456
description: 构建于工厂操作系统之上的数据认知中枢，通过对话式交互将分散的工业数据转化为可解释的业务洞察，让业务人员以自然语言直接探查全域数据资产，实现从数据资源到决策依据的即时转化。
icon: icon.png
dependencies:
